- name: put /root/k8s-openvpn-config.yaml
  template: src=k8s-openvpn-config.yaml dest=/root/k8s-openvpn-config.yaml

- name: create /data/pvs
  file: dest=/data/pvs state=directory owner=root mode=0600

- name: put an openvpn-pv1.yaml file
  template: src=pv1.yaml dest=/root/openvpn-pv1.yaml

- name: check if a PV exist
  shell: kubectl get persistentvolumes --namespace={{ openvpn_namespace }} | grep openvpn-data-1
  register: result
  ignore_errors: true

- name: deploy a persistent volume
  shell: kubectl create --namespace={{ openvpn_namespace }} -f /root/openvpn-pv1.yaml
  when: result|failed

- name: check if a Helm release for openvpn is present
  shell: helm list --namespace={{ openvpn_namespace }} | grep openvpn-release
  register: result
  ignore_errors: true

- name: enable the incubator repo
  shell: helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/

- name: clone the repo
  git: repo=https://github.com/alexclear/charts.git version=openvpn-statefulset dest=/root/charts

- name: install an OpenVPN instance using a Helm chart
  shell: cd /root/charts/stable && helm install -f /root/k8s-openvpn-config.yaml openvpn --namespace {{ openvpn_namespace }} --name openvpn-release
  when: result|failed
